// This file auto imports all the sites in this folder (except files that start with a dot or underscore), do NOT edit this file
//import { ERROR } from "../../classes/Functions";
import { Site } from "../../classes/Site";
/* __AUTOLOAD_SITE_IMPORTER__ */

let sites: Site[] = [];
/* __AUTOLOAD_SITE_PUSHER__ */

export default sites.filter((site) => {
  const status = site instanceof Site;
  if (!status) {
    throw new Error(
      `[MV] Provided site is not an instance of the Site class! || ${String(
        site
      )}`
    );
  }
  return status;
});
